#!/bin/sh
set -e

CONFIG_FILE="/var/www/html/includes/config.php"

# Generate includes/config.php from environment variables on every boot.
# Coolify env vars are the source of truth.
cat > "$CONFIG_FILE" <<'PHP'
<?php
// Auto-generated by docker/entrypoint.sh from environment variables.
// Do not edit by hand inside the container — change Coolify env vars instead.

if (!defined('JINKA_ACCESS')) {
    define('JINKA_ACCESS', true);
}

$envBool = function ($key, $default = false) {
    $v = getenv($key);
    if ($v === false || $v === '') return $default;
    return in_array(strtolower($v), ['1', 'true', 'yes', 'on'], true);
};
$envStr = function ($key, $default = '') {
    $v = getenv($key);
    return ($v === false) ? $default : $v;
};
$envInt = function ($key, $default = 0) {
    $v = getenv($key);
    return ($v === false || $v === '') ? $default : (int) $v;
};

// Environment
define('ENVIRONMENT', $envStr('ENVIRONMENT', 'production'));
define('DEBUG_MODE', $envBool('DEBUG_MODE', false));

// Database
define('DB_HOST', $envStr('DB_HOST', 'localhost'));
define('DB_NAME', $envStr('DB_NAME', ''));
define('DB_USER', $envStr('DB_USER', ''));
define('DB_PASS', $envStr('DB_PASS', ''));
define('DB_CHARSET', $envStr('DB_CHARSET', 'utf8mb4'));

// Security
define('SECRET_KEY', $envStr('SECRET_KEY', ''));
define('ENCRYPTION_KEY', $envStr('ENCRYPTION_KEY', ''));
define('SESSION_TIMEOUT', $envInt('SESSION_TIMEOUT', 3600));
define('SESSION_NAME', $envStr('SESSION_NAME', 'JINKASESSID'));

// Site
define('SITE_URL', $envStr('SITE_URL', 'https://ndosa.store'));
define('SITE_NAME', $envStr('SITE_NAME', 'JINKA Plotter'));

// Paths
define('UPLOAD_PATH', $envStr('UPLOAD_PATH', './uploads'));
define('MAX_FILE_SIZE', $envInt('MAX_FILE_SIZE', 10485760));
define('CACHE_ENABLED', $envBool('CACHE_ENABLED', true));
define('CACHE_DURATION', $envInt('CACHE_DURATION', 3600));
define('CACHE_PATH', $envStr('CACHE_PATH', './cache'));
define('LOG_ENABLED', $envBool('LOG_ENABLED', true));
define('LOG_PATH', $envStr('LOG_PATH', './logs'));

// Email
define('SMTP_HOST', $envStr('SMTP_HOST', ''));
define('SMTP_PORT', $envInt('SMTP_PORT', 587));
define('SMTP_USERNAME', $envStr('SMTP_USERNAME', ''));
define('SMTP_PASSWORD', $envStr('SMTP_PASSWORD', ''));
define('SMTP_FROM_EMAIL', $envStr('SMTP_FROM_EMAIL', ''));
define('FROM_EMAIL', $envStr('FROM_EMAIL', ''));
define('ADMIN_EMAIL', $envStr('ADMIN_EMAIL', ''));

// Business info
define('BUSINESS_EMAIL', $envStr('BUSINESS_EMAIL', ''));
define('BUSINESS_PHONE_TZ', $envStr('BUSINESS_PHONE_TZ', ''));
define('BUSINESS_PHONE_KE', $envStr('BUSINESS_PHONE_KE', ''));
define('WHATSAPP_NUMBER', $envStr('WHATSAPP_NUMBER', ''));

// Payments
define('PAYMENT_USE_SANDBOX', $envBool('PAYMENT_USE_SANDBOX', false));

define('PESAPAL_CONSUMER_KEY', $envStr('PESAPAL_CONSUMER_KEY', ''));
define('PESAPAL_CONSUMER_SECRET', $envStr('PESAPAL_CONSUMER_SECRET', ''));
define('PESAPAL_IPN_ID', $envStr('PESAPAL_IPN_ID', ''));

define('FLUTTERWAVE_PUBLIC_KEY', $envStr('FLUTTERWAVE_PUBLIC_KEY', ''));
define('FLUTTERWAVE_SECRET_KEY', $envStr('FLUTTERWAVE_SECRET_KEY', ''));
define('FLUTTERWAVE_ENCRYPTION_KEY', $envStr('FLUTTERWAVE_ENCRYPTION_KEY', ''));

define('AZAMPAY_CLIENT_ID', $envStr('AZAMPAY_CLIENT_ID', ''));
define('AZAMPAY_CLIENT_SECRET', $envStr('AZAMPAY_CLIENT_SECRET', ''));
define('AZAMPAY_API_KEY', $envStr('AZAMPAY_API_KEY', ''));
define('AZAMPAY_ACCOUNT_NUMBER', $envStr('AZAMPAY_ACCOUNT_NUMBER', ''));

define('MPESA_CONSUMER_KEY', $envStr('MPESA_CONSUMER_KEY', ''));
define('MPESA_CONSUMER_SECRET', $envStr('MPESA_CONSUMER_SECRET', ''));
define('MPESA_SHORTCODE', $envStr('MPESA_SHORTCODE', ''));
define('MPESA_PASSKEY', $envStr('MPESA_PASSKEY', ''));

define('PAYPAL_CLIENT_ID', $envStr('PAYPAL_CLIENT_ID', ''));
define('PAYPAL_CLIENT_SECRET', $envStr('PAYPAL_CLIENT_SECRET', ''));
define('PAYPAL_WEBHOOK_ID', $envStr('PAYPAL_WEBHOOK_ID', ''));

define('STRIPE_PUBLISHABLE_KEY', $envStr('STRIPE_PUBLISHABLE_KEY', ''));
define('STRIPE_SECRET_KEY', $envStr('STRIPE_SECRET_KEY', ''));
define('STRIPE_WEBHOOK_SECRET', $envStr('STRIPE_WEBHOOK_SECRET', ''));

// Firebase
define('FIREBASE_API_KEY', $envStr('FIREBASE_API_KEY', ''));
define('FIREBASE_AUTH_DOMAIN', $envStr('FIREBASE_AUTH_DOMAIN', ''));
define('FIREBASE_PROJECT_ID', $envStr('FIREBASE_PROJECT_ID', ''));
define('FIREBASE_STORAGE_BUCKET', $envStr('FIREBASE_STORAGE_BUCKET', ''));
define('FIREBASE_MESSAGING_SENDER_ID', $envStr('FIREBASE_MESSAGING_SENDER_ID', ''));
define('FIREBASE_APP_ID', $envStr('FIREBASE_APP_ID', ''));

// Error reporting
if (DEBUG_MODE) {
    error_reporting(E_ALL);
    ini_set('display_errors', '1');
} else {
    error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
    ini_set('display_errors', '0');
    ini_set('log_errors', '1');
}

// ---------------------------------------------------------------------------
// Class autoloader: load any class from /var/www/html/includes/<Name>.php.
// The original config (gitignored) presumably did the same.
// ---------------------------------------------------------------------------
spl_autoload_register(function ($class) {
    $base = __DIR__; // .../includes
    $candidates = [
        $base . '/' . $class . '.php',
        $base . '/payments/' . $class . '.php',
    ];
    foreach ($candidates as $file) {
        if (is_file($file)) {
            require_once $file;
            return;
        }
    }
});

// ---------------------------------------------------------------------------
// Database singleton (MySQLi). Originally lived in a gitignored config file;
// recreated here so the app boots in a clean container.
// ---------------------------------------------------------------------------
class Database {
    private static $instance = null;
    private $conn;

    private function __construct() {
        mysqli_report(MYSQLI_REPORT_OFF);
        $this->conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
        if ($this->conn->connect_error) {
            error_log('DB connect failed: ' . $this->conn->connect_error);
            throw new RuntimeException('Database connection failed');
        }
        $this->conn->set_charset(DB_CHARSET);
    }

    public static function getInstance() {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    public function getConnection() {
        return $this->conn;
    }
}

// ---------------------------------------------------------------------------
// site_setting(): read a row from the `settings` table, with a default.
// Cached per-request to avoid hammering the DB.
// ---------------------------------------------------------------------------
// ---------------------------------------------------------------------------
// Security: CSRF, password hashing, input sanitisation. Used heavily by the
// admin panel. Was in the gitignored config; rebuilt here.
// ---------------------------------------------------------------------------
if (!class_exists('Security')) {
    class Security {
        const CSRF_KEY = '_csrf_token';

        public static function generateCSRFToken() {
            if (session_status() !== PHP_SESSION_ACTIVE) @session_start();
            if (empty($_SESSION[self::CSRF_KEY])) {
                $_SESSION[self::CSRF_KEY] = bin2hex(random_bytes(32));
            }
            return $_SESSION[self::CSRF_KEY];
        }

        public static function verifyCSRFToken($token) {
            if (session_status() !== PHP_SESSION_ACTIVE) @session_start();
            return !empty($_SESSION[self::CSRF_KEY])
                && is_string($token)
                && hash_equals($_SESSION[self::CSRF_KEY], $token);
        }

        public static function hashPassword($password) {
            return password_hash($password, PASSWORD_BCRYPT, ['cost' => 12]);
        }

        public static function verifyPassword($password, $hash) {
            return password_verify($password, $hash);
        }

        public static function sanitizeInput($value) {
            if (is_array($value)) return array_map([self::class, 'sanitizeInput'], $value);
            $value = (string)$value;
            $value = trim($value);
            // Strip control characters but keep newlines/tabs
            $value = preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/u', '', $value);
            return $value;
        }
    }
}

// ---------------------------------------------------------------------------
// Logger: lightweight structured logger writing to LOG_PATH/app.log.
// ---------------------------------------------------------------------------
if (!class_exists('Logger')) {
    class Logger {
        private static function write($level, $message, array $context = []) {
            if (!defined('LOG_ENABLED') || !LOG_ENABLED) return;
            $dir = defined('LOG_PATH') ? LOG_PATH : __DIR__ . '/../logs';
            if (!is_dir($dir)) @mkdir($dir, 0775, true);
            $line = sprintf(
                "[%s] %s: %s %s\n",
                date('Y-m-d H:i:s'),
                strtoupper($level),
                $message,
                $context ? json_encode($context) : ''
            );
            @file_put_contents($dir . '/app.log', $line, FILE_APPEND | LOCK_EX);
        }
        public static function info($message, array $context = [])    { self::write('info',    $message, $context); }
        public static function warning($message, array $context = []) { self::write('warning', $message, $context); }
        public static function error($message, array $context = [])   { self::write('error',   $message, $context); }
        public static function debug($message, array $context = [])   { self::write('debug',   $message, $context); }
    }
}

// ---------------------------------------------------------------------------
// redirect(): admin/login.php and friends use redirect($path, $msg, $type)
// to issue a Location header with an optional flash message.
// ---------------------------------------------------------------------------
if (!function_exists('redirect')) {
    function redirect($path, $message = '', $type = 'info') {
        if (session_status() !== PHP_SESSION_ACTIVE) @session_start();
        if ($message !== '') {
            $_SESSION['flash'] = ['message' => $message, 'type' => $type];
        }
        if (!headers_sent()) {
            header('Location: ' . $path);
        }
        exit;
    }
}

if (!function_exists('flash_get')) {
    function flash_get() {
        if (session_status() !== PHP_SESSION_ACTIVE) @session_start();
        if (!empty($_SESSION['flash'])) {
            $f = $_SESSION['flash'];
            unset($_SESSION['flash']);
            return $f;
        }
        return null;
    }
}

if (!function_exists('site_url')) {
    function site_url($path = '') {
        $base = rtrim(SITE_URL, '/');
        if ($path === '' || $path === null) {
            return $base . '/';
        }
        if (preg_match('#^https?://#i', $path)) {
            return $path;
        }
        return $base . '/' . ltrim($path, '/');
    }
}

if (!function_exists('current_url')) {
    function current_url() {
        $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
            || (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https')
            ? 'https' : 'http';
        $host = $_SERVER['HTTP_HOST'] ?? parse_url(SITE_URL, PHP_URL_HOST);
        $uri = $_SERVER['REQUEST_URI'] ?? '/';
        return $scheme . '://' . $host . $uri;
    }
}

if (!function_exists('esc_html')) {
    function esc_html($value) {
        return htmlspecialchars((string)$value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }
}

if (!function_exists('normalize_product_image_url')) {
    function normalize_product_image_url($source, array $options = []) {
        $fallback = $options['fallback'] ?? '';
        $absolute = !empty($options['absolute']);
        $url = trim((string)$source);
        if ($url === '') {
            $url = $fallback;
        }
        if ($url === '') {
            return '';
        }
        if (preg_match('#^https?://#i', $url)) {
            return $url;
        }
        $url = ltrim($url, '/');
        if ($absolute) {
            return rtrim(SITE_URL, '/') . '/' . $url;
        }
        return $url;
    }
}

if (!function_exists('site_setting')) {
    function site_setting($key, $default = '') {
        static $cache = null;
        if ($cache === null) {
            $cache = [];
            try {
                $db = Database::getInstance()->getConnection();
                $res = @$db->query('SELECT setting_key, setting_value FROM settings');
                if ($res) {
                    while ($row = $res->fetch_assoc()) {
                        $cache[$row['setting_key']] = $row['setting_value'];
                    }
                }
            } catch (Throwable $e) {
                error_log('site_setting load failed: ' . $e->getMessage());
            }
        }
        return array_key_exists($key, $cache) ? $cache[$key] : $default;
    }
}
PHP

chown www-data:www-data "$CONFIG_FILE"
chmod 640 "$CONFIG_FILE"

# Make sure runtime dirs exist & are writable (volumes may be empty on first boot)
for d in uploads cache logs; do
    mkdir -p "/var/www/html/$d"
    chown -R www-data:www-data "/var/www/html/$d"
    chmod -R 775 "/var/www/html/$d"
done

# One-shot DB migration. Marker lives in the logs volume so it survives redeploys.
MIGRATED_MARKER=/var/www/html/logs/.migrated
# If a previous boot touched the marker but the import actually failed (e.g. TLS),
# the FORCE_MIGRATE env var lets us redo it.
if [ "${FORCE_MIGRATE:-0}" = "1" ]; then
    rm -f "$MIGRATED_MARKER"
fi
if [ -n "$DB_HOST" ] && [ -n "$DB_NAME" ] && [ ! -f "$MIGRATED_MARKER" ]; then
    echo "[entrypoint] Running first-boot DB migration..."
    # Wait for MySQL to be reachable
    for i in $(seq 1 30); do
        if mysqladmin --ssl=0 ping -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" --silent 2>/dev/null; then
            break
        fi
        echo "[entrypoint] Waiting for MySQL ($i/30)..."
        sleep 2
    done

    cd /var/www/html
    # schema.sql contains stray CREATE DATABASE / USE statements pointing at a
    # different db name; strip them so it imports into $DB_NAME.
    for f in \
        database/schema.sql \
        database/create-customer-tables.sql \
        database/create-order-items-table.sql \
        database/create_deliveries_table.sql \
        database/support_system.sql \
        database/theme_settings.sql \
        database/product_relationships.sql \
        database/add-firebase-auth-fields.sql \
        database/add-phone-verification.sql \
        database/add_mpesa_fields.sql \
        database/add-indexes-safe.sql \
        database/add-performance-indexes.sql; do
        if [ -f "$f" ]; then
            echo "[entrypoint] Importing $f"
            sed -e '/^CREATE DATABASE/d' -e '/^USE /d' \
                -e '/^START TRANSACTION/d' -e '/^COMMIT/d' "$f" \
                | mysql --ssl=0 --force -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
                2>&1 | sed "s/^/    [$f] /" \
                || echo "[entrypoint] (non-fatal error in $f, continuing)"
        fi
    done
    touch "$MIGRATED_MARKER"
    chown www-data:www-data "$MIGRATED_MARKER"
    echo "[entrypoint] Migration complete."
else
    [ -f "$MIGRATED_MARKER" ] && echo "[entrypoint] DB already migrated, skipping."
fi

exec "$@"
