#!/bin/sh
set -e

CONFIG_FILE="/var/www/html/includes/config.php"

# Generate includes/config.php from environment variables on every boot.
# Coolify env vars are the source of truth.
cat > "$CONFIG_FILE" <<'PHP'
<?php
// Auto-generated by docker/entrypoint.sh from environment variables.
// Do not edit by hand inside the container — change Coolify env vars instead.

if (!defined('JINKA_ACCESS')) {
    define('JINKA_ACCESS', true);
}

$envBool = function ($key, $default = false) {
    $v = getenv($key);
    if ($v === false || $v === '') return $default;
    return in_array(strtolower($v), ['1', 'true', 'yes', 'on'], true);
};
$envStr = function ($key, $default = '') {
    $v = getenv($key);
    return ($v === false) ? $default : $v;
};
$envInt = function ($key, $default = 0) {
    $v = getenv($key);
    return ($v === false || $v === '') ? $default : (int) $v;
};

// Environment
define('ENVIRONMENT', $envStr('ENVIRONMENT', 'production'));
define('DEBUG_MODE', $envBool('DEBUG_MODE', false));

// Database
define('DB_HOST', $envStr('DB_HOST', 'localhost'));
define('DB_NAME', $envStr('DB_NAME', ''));
define('DB_USER', $envStr('DB_USER', ''));
define('DB_PASS', $envStr('DB_PASS', ''));
define('DB_CHARSET', $envStr('DB_CHARSET', 'utf8mb4'));

// Security
define('SECRET_KEY', $envStr('SECRET_KEY', ''));
define('ENCRYPTION_KEY', $envStr('ENCRYPTION_KEY', ''));
define('SESSION_TIMEOUT', $envInt('SESSION_TIMEOUT', 3600));
define('SESSION_NAME', $envStr('SESSION_NAME', 'JINKASESSID'));

// Site
define('SITE_URL', $envStr('SITE_URL', 'https://ndosa.store'));
define('SITE_NAME', $envStr('SITE_NAME', 'JINKA Plotter'));

// Paths
define('UPLOAD_PATH', $envStr('UPLOAD_PATH', './uploads'));
define('MAX_FILE_SIZE', $envInt('MAX_FILE_SIZE', 10485760));
define('CACHE_ENABLED', $envBool('CACHE_ENABLED', true));
define('CACHE_DURATION', $envInt('CACHE_DURATION', 3600));
define('CACHE_PATH', $envStr('CACHE_PATH', './cache'));
define('LOG_ENABLED', $envBool('LOG_ENABLED', true));
define('LOG_PATH', $envStr('LOG_PATH', './logs'));

// Email
define('SMTP_HOST', $envStr('SMTP_HOST', ''));
define('SMTP_PORT', $envInt('SMTP_PORT', 587));
define('SMTP_USERNAME', $envStr('SMTP_USERNAME', ''));
define('SMTP_PASSWORD', $envStr('SMTP_PASSWORD', ''));
define('SMTP_FROM_EMAIL', $envStr('SMTP_FROM_EMAIL', ''));
define('FROM_EMAIL', $envStr('FROM_EMAIL', ''));
define('ADMIN_EMAIL', $envStr('ADMIN_EMAIL', ''));

// Business info
define('BUSINESS_EMAIL', $envStr('BUSINESS_EMAIL', ''));
define('BUSINESS_PHONE_TZ', $envStr('BUSINESS_PHONE_TZ', ''));
define('BUSINESS_PHONE_KE', $envStr('BUSINESS_PHONE_KE', ''));
define('WHATSAPP_NUMBER', $envStr('WHATSAPP_NUMBER', ''));

// Payments
define('PAYMENT_USE_SANDBOX', $envBool('PAYMENT_USE_SANDBOX', false));

define('PESAPAL_CONSUMER_KEY', $envStr('PESAPAL_CONSUMER_KEY', ''));
define('PESAPAL_CONSUMER_SECRET', $envStr('PESAPAL_CONSUMER_SECRET', ''));
define('PESAPAL_IPN_ID', $envStr('PESAPAL_IPN_ID', ''));

define('FLUTTERWAVE_PUBLIC_KEY', $envStr('FLUTTERWAVE_PUBLIC_KEY', ''));
define('FLUTTERWAVE_SECRET_KEY', $envStr('FLUTTERWAVE_SECRET_KEY', ''));
define('FLUTTERWAVE_ENCRYPTION_KEY', $envStr('FLUTTERWAVE_ENCRYPTION_KEY', ''));

define('AZAMPAY_CLIENT_ID', $envStr('AZAMPAY_CLIENT_ID', ''));
define('AZAMPAY_CLIENT_SECRET', $envStr('AZAMPAY_CLIENT_SECRET', ''));
define('AZAMPAY_API_KEY', $envStr('AZAMPAY_API_KEY', ''));
define('AZAMPAY_ACCOUNT_NUMBER', $envStr('AZAMPAY_ACCOUNT_NUMBER', ''));

define('MPESA_CONSUMER_KEY', $envStr('MPESA_CONSUMER_KEY', ''));
define('MPESA_CONSUMER_SECRET', $envStr('MPESA_CONSUMER_SECRET', ''));
define('MPESA_SHORTCODE', $envStr('MPESA_SHORTCODE', ''));
define('MPESA_PASSKEY', $envStr('MPESA_PASSKEY', ''));

define('PAYPAL_CLIENT_ID', $envStr('PAYPAL_CLIENT_ID', ''));
define('PAYPAL_CLIENT_SECRET', $envStr('PAYPAL_CLIENT_SECRET', ''));
define('PAYPAL_WEBHOOK_ID', $envStr('PAYPAL_WEBHOOK_ID', ''));

define('STRIPE_PUBLISHABLE_KEY', $envStr('STRIPE_PUBLISHABLE_KEY', ''));
define('STRIPE_SECRET_KEY', $envStr('STRIPE_SECRET_KEY', ''));
define('STRIPE_WEBHOOK_SECRET', $envStr('STRIPE_WEBHOOK_SECRET', ''));

// Firebase
define('FIREBASE_API_KEY', $envStr('FIREBASE_API_KEY', ''));
define('FIREBASE_AUTH_DOMAIN', $envStr('FIREBASE_AUTH_DOMAIN', ''));
define('FIREBASE_PROJECT_ID', $envStr('FIREBASE_PROJECT_ID', ''));
define('FIREBASE_STORAGE_BUCKET', $envStr('FIREBASE_STORAGE_BUCKET', ''));
define('FIREBASE_MESSAGING_SENDER_ID', $envStr('FIREBASE_MESSAGING_SENDER_ID', ''));
define('FIREBASE_APP_ID', $envStr('FIREBASE_APP_ID', ''));

// Error reporting
if (DEBUG_MODE) {
    error_reporting(E_ALL);
    ini_set('display_errors', '1');
} else {
    error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
    ini_set('display_errors', '0');
    ini_set('log_errors', '1');
}
PHP

chown www-data:www-data "$CONFIG_FILE"
chmod 640 "$CONFIG_FILE"

# Make sure runtime dirs exist & are writable (volumes may be empty on first boot)
for d in uploads cache logs; do
    mkdir -p "/var/www/html/$d"
    chown -R www-data:www-data "/var/www/html/$d"
    chmod -R 775 "/var/www/html/$d"
done

# One-shot DB migration. Marker lives in the logs volume so it survives redeploys.
MIGRATED_MARKER=/var/www/html/logs/.migrated
# If a previous boot touched the marker but the import actually failed (e.g. TLS),
# the FORCE_MIGRATE env var lets us redo it.
if [ "${FORCE_MIGRATE:-0}" = "1" ]; then
    rm -f "$MIGRATED_MARKER"
fi
if [ -n "$DB_HOST" ] && [ -n "$DB_NAME" ] && [ ! -f "$MIGRATED_MARKER" ]; then
    echo "[entrypoint] Running first-boot DB migration..."
    # Wait for MySQL to be reachable
    for i in $(seq 1 30); do
        if mysqladmin --ssl=0 ping -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" --silent 2>/dev/null; then
            break
        fi
        echo "[entrypoint] Waiting for MySQL ($i/30)..."
        sleep 2
    done

    cd /var/www/html
    # schema.sql contains stray CREATE DATABASE / USE statements pointing at a
    # different db name; strip them so it imports into $DB_NAME.
    for f in \
        database/schema.sql \
        database/create-customer-tables.sql \
        database/create-order-items-table.sql \
        database/create_deliveries_table.sql \
        database/support_system.sql \
        database/theme_settings.sql \
        database/product_relationships.sql \
        database/add-firebase-auth-fields.sql \
        database/add-phone-verification.sql \
        database/add_mpesa_fields.sql \
        database/add-indexes-safe.sql \
        database/add-performance-indexes.sql; do
        if [ -f "$f" ]; then
            echo "[entrypoint] Importing $f"
            sed -e '/^CREATE DATABASE/d' -e '/^USE /d' "$f" \
                | mysql --ssl=0 -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
                || echo "[entrypoint] (non-fatal error in $f, continuing)"
        fi
    done
    touch "$MIGRATED_MARKER"
    chown www-data:www-data "$MIGRATED_MARKER"
    echo "[entrypoint] Migration complete."
else
    [ -f "$MIGRATED_MARKER" ] && echo "[entrypoint] DB already migrated, skipping."
fi

exec "$@"
